name: GitHub Profile Summary Cards

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/profile-summary-cards.yml
      - README.md
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: devWelby
          THEME: github_dark
          BRANCH_NAME: main
          UTC_OFFSET: -3
          AUTO_PUSH: true
          EXCLUDE: ""
